### PR TITLE
Make it work with Quartus II

### PR DESCRIPTION
**Pull request by gyurco**
Unfortunately something wrong: seems the CPU is stuck, and the whole ikbd module is optimized out (I've connected the PS2 ports to user_io, and rx/tx to UART_RX/UART_TX, or the MIDI ACIA, so they're not dangling).

### CODE REVIEW

**Comment by gyurco** [comment]
I've attached SignalTap II, and at least the CPU is now not optimized out. Fits nicely, uses 8 M9Ks (even the microcode is inferred into BRAM). Seems the address bus is incremented, ROM data is read, however PO2 is stuck at 0xFF (the boot OK should be transmitted at least?).

**Comment by gyurco** [comment]
This part looks funny:
https://github.com/harbaum/ikbd/blob/7b8c40f05c3a3a6a6072628b9503bb5a080955ae/hd63701/HD63701_EXEC.v#L173
Removing the async reset allows the CPU to run (and po[4] -tx- is changing actually)

**Comment by gyurco** [comment]
Now it writes F1 to 0013h after reset.

**Comment by gyurco** [comment]
And finally it works! It's so exciting! Only had to exchange the mouse buttons, and invert the Y direction.
Pushed the core changes into my repo. It needs the firmware update, currently in a pull request for the mist-firmware repo.
Just one personal wish: mouse X movement should be a bit faster.

Another thing where I have some doubts: now I had to invert the tx/rx data in ACIA (which seems to be correct, since RS232 is negative logic). However MIDI worked without that. Now the IKBD/MIDI transmitters/receivers are the same, is MIDI still works?

**Comment by gyurco** [comment]
One issue found: when there's extensive bi-directional communication (e.g. the CPU sends a command constantly to the ikbd), heavy mouse using can make ikbd stuck. Reproducible in Defender of the Crown: just start the game, choose "Go raiding", select an opponent castle. Then click and move the mouse like crazy, and sooner or later the controls are gone. Captured with Signal Tap II, the game sends constantly 0x08 command, and after a while, nothing will returned by ikbd (and after that, even the sending will cause serial overrun - not framing error -  in the ikbd's MCU).

**Comment by gyurco** [comment]
Maybe I could reproduce it with the testbench:
````
@292418.25µs IKBD RX 04 => MOUSE X 4=45
@293698.25µs IKBD RX fc => MOUSE Y -4=-55
@294978.25µs IKBD RX f9 => MOUSE REL L:on R:off
@296258.25µs IKBD RX 04 => MOUSE X 4=49
@297538.25µs IKBD RX fc => MOUSE Y -4=-59
@298818.25µs IKBD RX f9 => MOUSE REL L:on R:off
@300000.00µs PS2 TX 0a                     <======= Look at this
@300098.25µs IKBD RX 03 => MOUSE X 3=52
@301378.25µs IKBD RX fd => MOUSE Y -3=-62
@302658.25µs IKBD RX f9 => MOUSE REL L:on R:off
@303938.25µs IKBD RX 04 => MOUSE X 4=56
@305218.25µs IKBD RX fc => MOUSE Y -4=-66
@306498.25µs IKBD RX f9 => MOUSE REL L:on R:off
@307778.25µs IKBD RX 04 => MOUSE X 4=60
@309058.25µs IKBD RX fc => MOUSE Y -4=-70
@310338.25µs IKBD RX f9 => MOUSE REL L:on R:off
@311618.25µs IKBD RX 04 => MOUSE X 4=64
@312898.25µs IKBD RX fc => MOUSE Y -4=-74
@314178.25µs IKBD RX f9 => MOUSE REL L:on R:off
.
.
.
@346178.25µs IKBD RX 00 => MOUSE X 0=65
@347458.25µs IKBD RX fc => MOUSE Y -4=-108
@348738.25µs IKBD RX f9 => MOUSE REL L:on R:off
@80000.00µs Test relative mouse movement
@80000.00µs Should end at X:-10, Y:10
@90000.00µs IKBD TX 08
@91408.00µs IKBD TX 01
@100000.00µs PS2 TX 09
@100918.50µs PS2 TX 0a
@101837.00µs PS2 TX 14
@200000.00µs PS2 TX 0a

````
No more IKBD RX. So probably just the PS2 mouse state machine got stuck. Maybe a timeout to reset it in state 1 or state 2 is enough to fix.

That was the test case (and modified the test runner to just loop forever)
````
#if 1 // relative mouse
#define RUNTIME_MS 350
  {   80, TTEXT, (unsigned char*)"Test relative mouse movement" },
  {   80, TTEXT, (unsigned char*)"Should end at X:-10, Y:10" },
  {   90, TSER, cmd_set_relative_mouse_positioning },
  {  100, TPS2M, io_ps2_mouse_up_right },
  {  200, TPS2M, io_ps2_mouse_button_right },
  {  250, TPS2M, io_ps2_mouse_down_left },
  {  300, TPS2M, io_ps2_mouse_button_right },
  // should end at x:-10,y:10
#endif
````

**Comment by gyurco** [comment]
Unfortunately the problem is something else. No idea what happened inside the ikbd CPU, it still runs, but not handling IO.

**Comment by harbaum** [comment]
I indeed missed this one. Too great. I'll have a look at the issues.

**Comment by harbaum** [comment]
The MIST MIDI hardware is exactly the same as on a Atari ST so there's no additional inverter or the like.The ACIAs output should imho be 1 (high) if nothing is being transmitted. The start bit is 0/low and during transmission 0's are low and 1's are high. Maybe i confused that ...

**Comment by gyurco** [comment]
I had to invert the data only, the stop/start bits were OK. So probably it's wrong in ikbd, since MIDI worked without the change.
I still didn't find the reason, why ikbd freeze in DOC swordfighting :( Hope not another CPU bug. Maybe overwhelmed by mouse events, and should be rate limited?

**Comment by harbaum** [comment]
I just fixed the data polarity. Your test case seems to trigger something if new mouse data arrives while the previous one is still being processed.

The interesting thing about dotc is that it imho was even broken in my very old mist core. 

One thing that might need tweaking is the rate at which mouse pulses are generated internally. I'll make that part adjustable.

**Comment by harbaum** [comment]
Does sword fight only crash when you use the mouse very fast? That may be hard to track down ... I could hack hatari into reporting mouse events and replay that into my simulation.

**Comment by gyurco** [comment]
More like clicking fast, while moving left and right.
The CPU side continously transfer 0x08, 0x00 (don't know why the 0x00, it's NOP AFAIK).
 Yeah, DOTC has some quirks, but I know this part was working with the ARM IKBD controller.
In the data polarity fix, you changed all the bits? Since only the 8-bit data part was inverted compared to MIDI, stop and start bits were OK.
Btw, I've tried some things, the mouse_event_cnt was better if it was 10 bit (/1024 - 2000steps/sec), and mouse_sr divided by 4 (e.g. using mouse_sr[7:2] only). These changes made the mouse movement a bit more "natural". However didn't fix the bug.

**Comment by harbaum** [comment]
I only inverted the data bits.

**Comment by gyurco** [comment]
Indeed. Inverted ACIA back.

**Comment by gyurco** [comment]
I think I found it: the interrupts should be level-triggered according to the datasheet, however the core handles them as edge triggered. So if they're disabled, then they'll lost forever.
Changing this: https://github.com/harbaum/ikbd/blob/master/hd63701/HD63701_SEQ.v#L138
to simply fINT[0] <= IRQ0 fixes the mouse freeze in DOTC. Must revise the other ones, too, probably you know more about the internals already, you can fix it more properly.

**Comment by harbaum** [comment]
I've removed all the IRQ edge/latch stuff and the tests all still run. My only concern would have been that this would cause IRQs to interrupt each other. But that seems to be prevented by the inte signal.

**Comment by gyurco** [comment]
Maybe it has a priority system. And servicing an interrupt usually disable the others until re-enabled by the code. But would need to check the datasheet for the intended operation, I guess. Yesterday I read it briefly, but found only IRQ1 and IRQ2 mentioned, no IRQ0. However it was too late and I was very sleepy already :)

**Comment by harbaum** [comment]
It has a priority system and that's still implemented at https://github.com/harbaum/ikbd/blob/master/hd63701/HD63701_SEQ.v#L42

And yes, there is no IRQ0 instead the IRQ2 consists if several different IRQs which also all have a priority. The current solution is not nice but it imho behaves like the real thing. I just renamed the irq2 to irq2_tim and irq0 to irq2_sci to make things a little clearer.

**Comment by harbaum** [comment]
Also i just added the missing key codes

**Comment by gyurco** [comment]
Cool! Is PrtScrn is a good idea? It has 2 codes, both are clashing with an other key.
Upd.: never mind, extended codes vs normal

**Comment by harbaum** [comment]
Sure? In simulation it works as expected. Which are they clashing with? Also this is what the arm ikbd does.

**Comment by gyurco** [comment]
Yeah, it's OK.
Went through the STE test cartridge, tried all keys. I have no Euro key, but I see it's mapped.
Maybe right ctrl should be also mapped to ctrl.
There are some exchanged keys:
- KP 9, right shift, Y

Pushed a firmware update for fixing the modifiers.

**Comment by gyurco** [comment]
An idea for the second joystick: the switch can be made automatic, if it senses a mouse movement, it should switch to mouse mode, and when the joystick moved, switch to joy mode. It works in some other cores, too (C64, MSX as I could recall).

**Comment by harbaum** [comment]
Yes. One of the first hardware i ever designed and built myself did exactly that with a real mouse and a real joystick.

Edit: Did just that ....

**Comment by gyurco** [comment]
Then it's truly nostalgic :)
Works well!

**Pull request merged**
